// Bundled content catalogues: the furniture (USDZ generated by
// scripts/ios/gen-usdz.mjs + the imported cabinet) and the "Change Color"
// swatches (procedural PBR textures from scripts/ios/gen-textures.mjs + colours).
// Sizes are the real bounding boxes in metres.

import Foundation
import simd

enum FurnitureCatalog {
    /// Real MOZU product models (kitchen + wardrobe cabinets) + the bundled home
    /// furnishings for a complete room.
    static let items: [FurnitureItem] = MozuModels.items + homeItems

    static let categories: [String] = MozuModels.categories + ["Seating", "Tables", "Storage", "Bedroom", "Decor"]

    static func items(in category: String) -> [FurnitureItem] { items.filter { $0.category == category } }

    /// Generated home furnishings (sofa, bed, tables…) authored in metres.
    static let homeItems: [FurnitureItem] = [
        FurnitureItem(id: "cabinet_tall", name: "Tall Wardrobe", category: "Storage",
                      usdzName: "cabinet_tall", size: SIMD3<Float>(0.45, 2.35, 0.58)),
        FurnitureItem(id: "bookshelf", name: "Oak Bookshelf", category: "Storage",
                      usdzName: "bookshelf", size: SIMD3<Float>(0.84, 2.0, 0.30)),
        FurnitureItem(id: "tv_console", name: "TV Console", category: "Storage",
                      usdzName: "tv_console", size: SIMD3<Float>(1.6, 0.50, 0.41)),
        FurnitureItem(id: "sofa_3seat", name: "3-Seat Sofa", category: "Seating",
                      usdzName: "sofa_3seat", size: SIMD3<Float>(2.12, 0.90, 0.95)),
        FurnitureItem(id: "dining_chair", name: "Dining Chair", category: "Seating",
                      usdzName: "dining_chair", size: SIMD3<Float>(0.45, 0.925, 0.45)),
        FurnitureItem(id: "dining_table", name: "Dining Table", category: "Tables",
                      usdzName: "dining_table", size: SIMD3<Float>(1.5, 0.755, 0.85)),
        FurnitureItem(id: "coffee_table", name: "Coffee Table", category: "Tables",
                      usdzName: "coffee_table", size: SIMD3<Float>(1.1, 0.43, 0.60)),
        FurnitureItem(id: "bed_queen", name: "Queen Bed", category: "Bedroom",
                      usdzName: "bed_queen", size: SIMD3<Float>(1.7, 1.05, 2.1)),
        FurnitureItem(id: "planter", name: "Plant", category: "Decor",
                      usdzName: "planter", size: SIMD3<Float>(0.525, 1.2, 0.50)),
        FurnitureItem(id: "rug", name: "Area Rug", category: "Decor",
                      usdzName: "rug", size: SIMD3<Float>(2.4, 0.02, 1.6)),
    ]
}

enum SwatchCatalog {
    /// rgba helper (sRGB 0…1).
    private static func c(_ r: Float, _ g: Float, _ b: Float) -> SIMD4<Float> { SIMD4<Float>(r, g, b, 1) }

    /// Built-in room-surface swatches + the imported MOZU finish collections
    /// (HUE / TOUCH / FABRIC / WOOD / GLOSSY / REAL — see MozuFinishes.swift).
    static let swatches: [Swatch] = builtIn + MozuFinishes.swatches

    private static let builtIn: [Swatch] = [
        // Marble
        Swatch(id: "marble_cream", name: "Cream Marble", category: .marble, textureName: "marble_cream"),
        Swatch(id: "marble_white", name: "Grey Marble", category: .marble, textureName: "marble_white"),
        // Wood
        Swatch(id: "oak", name: "Oak", category: .wood, textureName: "oak"),
        Swatch(id: "walnut", name: "Walnut", category: .wood, textureName: "walnut"),
        // Tile
        Swatch(id: "tile_ceramic", name: "Ceramic Tile", category: .tile, textureName: "tile_ceramic"),
        // Granite
        Swatch(id: "granite_grey", name: "Grey Granite", category: .granite, textureName: "granite_grey"),
        Swatch(id: "granite_black", name: "Black Granite", category: .granite, textureName: "granite_black"),
        // Finishes (plaster + plain)
        Swatch(id: "plaster", name: "Plaster", category: .finishes, textureName: "plaster"),
        // Colours
        Swatch(id: "col_white", name: "White", category: .color, textureName: nil, rgba: c(0.95, 0.95, 0.93)),
        Swatch(id: "col_beige", name: "Beige", category: .color, textureName: nil, rgba: c(0.84, 0.78, 0.67)),
        Swatch(id: "col_sage", name: "Sage", category: .color, textureName: nil, rgba: c(0.62, 0.68, 0.58)),
        Swatch(id: "col_charcoal", name: "Charcoal", category: .color, textureName: nil, rgba: c(0.25, 0.26, 0.28)),
        Swatch(id: "col_navy", name: "Navy", category: .color, textureName: nil, rgba: c(0.20, 0.27, 0.40)),
        Swatch(id: "col_terracotta", name: "Terracotta", category: .color, textureName: nil, rgba: c(0.79, 0.45, 0.34)),
    ]

    static func swatches(in category: SwatchCategory) -> [Swatch] { swatches.filter { $0.category == category } }
    static let defaultSwatchID = "oak"
}
