// MOZU product models (Kitchen + Wardrobe cabinets) imported from the real USDZ
// assets in Resources/Models. Generated by scripts/ios/import-mozu-models.mjs —
// dimensions are the true bounding boxes from each model's matching STEP file.
// USDZ are loaded at native (real-world) scale by ModelLoader; do not edit by hand.

import Foundation
import simd

enum MozuModels {
    static let items: [FurnitureItem] = [
        FurnitureItem(id: "KT01", name: "Tall Cabinet KT01", category: "Kitchen · Tall", usdzName: "KT01", size: SIMD3<Float>(0.605, 2.35, 0.936)),
        FurnitureItem(id: "KT02", name: "Tall Cabinet KT02", category: "Kitchen · Tall", usdzName: "KT02", size: SIMD3<Float>(0.605, 2.35, 1.128)),
        FurnitureItem(id: "KT03", name: "Tall Cabinet KT03", category: "Kitchen · Tall", usdzName: "KT03", size: SIMD3<Float>(0.604, 2.35, 0.759)),
        FurnitureItem(id: "KT04", name: "Tall Cabinet KT04", category: "Kitchen · Tall", usdzName: "KT04", size: SIMD3<Float>(0.6, 2.35, 0.842)),
        FurnitureItem(id: "KT05", name: "Tall Cabinet KT05", category: "Kitchen · Tall", usdzName: "KT05", size: SIMD3<Float>(0.603, 2.35, 1.167)),
        FurnitureItem(id: "KT06", name: "Tall Cabinet KT06", category: "Kitchen · Tall", usdzName: "KT06", size: SIMD3<Float>(0.906, 2.35, 0.835)),
        FurnitureItem(id: "KF01", name: "Base Cabinet KF01", category: "Kitchen · Base", usdzName: "KF01", size: SIMD3<Float>(0.455, 0.8, 0.6)),
        FurnitureItem(id: "KF02", name: "Base Cabinet KF02", category: "Kitchen · Base", usdzName: "KF02", size: SIMD3<Float>(0.455, 0.8, 0.607)),
        FurnitureItem(id: "KF03", name: "Base Cabinet KF03", category: "Kitchen · Base", usdzName: "KF03", size: SIMD3<Float>(0.45, 0.8, 0.601)),
        FurnitureItem(id: "KF04", name: "Base Cabinet KF04", category: "Kitchen · Base", usdzName: "KF04", size: SIMD3<Float>(0.564, 0.66, 0.477)),
        FurnitureItem(id: "KF05", name: "Base Cabinet KF05", category: "Kitchen · Base", usdzName: "KF05", size: SIMD3<Float>(0.9, 0.832, 0.614)),
        FurnitureItem(id: "KF06", name: "Base Cabinet KF06", category: "Kitchen · Base", usdzName: "KF06", size: SIMD3<Float>(0.9, 0.8, 0.6)),
        FurnitureItem(id: "KF07", name: "Base Cabinet KF07", category: "Kitchen · Base", usdzName: "KF07", size: SIMD3<Float>(0.9, 0.8, 0.6)),
        FurnitureItem(id: "KF08", name: "Base Cabinet KF08", category: "Kitchen · Base", usdzName: "KF08", size: SIMD3<Float>(1, 0.8, 0.6)),
        FurnitureItem(id: "KH01", name: "Wall Cabinet KH01", category: "Kitchen · Wall", usdzName: "KH01", size: SIMD3<Float>(0.455, 0.8, 0.597)),
        FurnitureItem(id: "KH02", name: "Wall Cabinet KH02", category: "Kitchen · Wall", usdzName: "KH02", size: SIMD3<Float>(0.909, 0.8, 0.537)),
        FurnitureItem(id: "KH03", name: "Wall Cabinet KH03", category: "Kitchen · Wall", usdzName: "KH03", size: SIMD3<Float>(0.455, 0.8, 0.597)),
        FurnitureItem(id: "KH04", name: "Wall Cabinet KH04", category: "Kitchen · Wall", usdzName: "KH04", size: SIMD3<Float>(0.9, 0.71, 0.333)),
        FurnitureItem(id: "W04", name: "Wardrobe W04", category: "Wardrobe · Main", usdzName: "W04", size: SIMD3<Float>(0.56, 2.4, 0.9)),
        FurnitureItem(id: "W05", name: "Wardrobe W05", category: "Wardrobe · Main", usdzName: "W05", size: SIMD3<Float>(0.58, 2.4, 0.9)),
        FurnitureItem(id: "W06", name: "Wardrobe W06", category: "Wardrobe · Main", usdzName: "W06", size: SIMD3<Float>(0.58, 2.4, 0.9)),
        FurnitureItem(id: "W07", name: "Wardrobe W07", category: "Wardrobe · Main", usdzName: "W07", size: SIMD3<Float>(0.58, 2.4, 0.9)),
        FurnitureItem(id: "W08", name: "Wardrobe W08", category: "Wardrobe · Main", usdzName: "W08", size: SIMD3<Float>(0.58, 2.4, 0.9)),
        FurnitureItem(id: "W09", name: "Wardrobe W09", category: "Wardrobe · Main", usdzName: "W09", size: SIMD3<Float>(0.58, 2.4, 0.9)),
        FurnitureItem(id: "W10", name: "Wardrobe W10", category: "Wardrobe · Main", usdzName: "W10", size: SIMD3<Float>(0.56, 2.4, 0.9)),
        FurnitureItem(id: "W_ADJ1", name: "Side Cabinet ADJ ADJ1", category: "Wardrobe · Side", usdzName: "W_ADJ1", size: SIMD3<Float>(0.45, 0.5, 0.58)),
        FurnitureItem(id: "W_ADJ2", name: "Side Cabinet ADJ ADJ2", category: "Wardrobe · Side", usdzName: "W_ADJ2", size: SIMD3<Float>(0.9, 0.5, 0.58)),
        FurnitureItem(id: "W01", name: "Side Cabinet W01", category: "Wardrobe · Side", usdzName: "W01", size: SIMD3<Float>(0.53, 2.35, 0.3)),
        FurnitureItem(id: "W02", name: "Side Cabinet W02", category: "Wardrobe · Side", usdzName: "W02", size: SIMD3<Float>(0.45, 2.35, 0.58)),
        FurnitureItem(id: "W03", name: "Side Cabinet W03", category: "Wardrobe · Side", usdzName: "W03", size: SIMD3<Float>(0.45, 2.35, 0.58))
    ]

    static let categories: [String] = [
        "Kitchen · Base", "Kitchen · Wall", "Kitchen · Tall", "Wardrobe · Main", "Wardrobe · Side",
    ]
}
